#!/usr/bin/perl
# Small script to print out the current debian package's
# build dependencies, one per line.
use strict;
use warnings;

my $os = $^O;

if ($os eq "linux" && eval { require Dpkg::Control::Info; require Dpkg::Deps; }) {
    if (eval {
    my $control = Dpkg::Control::Info->new();
    my $fields = $control->get_source();
    my $build_depends = deps_parse($fields->{'Build-Depends'});
    my $out = deps_concat($build_depends);
    $out =~ s/, /,/g;
    my @out = sort(split(',', $out));
    print join("\n", @out) . "\n";
    }) {
        exit(0);
    }
}

{
    # Get section of file between Build-Depends and Package:
    open(FILE, "debian/control") || die "can't find debian/control";
    my $ready = 0;
    my @out;
    while (<FILE>) {
        if (! $ready) {
            $ready = 1 if (/Build-Dep/);
        } else {
           last if (/Package:/);
           next if (/^#/);
           next if (/:/);
           # punt on alternatives... FIXME
           next if (/\|/);
           # Remove version specs
           s/\([^)]*\)//;
           # Replace commas with whitespace
           y/,/ /;
           push(@out, split(" "));
       }
    }
    print join("\n", sort(@out)) . "\n";
}
