#!/bin/sh
# Commands related to building or installing Oblong packages on Linux, Mac, and Windows
# FIXME: hoist them out of obs_funcs.sh into individual files so we don't need this wrapper?
set -e

usage() {
    echo "Usage: obs verb [args]"
    echo "obs install pkg ...         - on mac or windows, install latest version of given packages from $MASTER"
    echo "obs yovo2yoversion VERSION  - look up which version of yobuild the given version of yovo depends on"
    echo "obs yovo2cefversion VERSION - look up which version of cef the given version of yovo (well, webthing) depends on"
    echo "obs detect_os               - get our os type/version identifier for the current os"
}

do_install() {
    for pkg
    do
        bs_install $pkg
    done
}

# FIXME: instead of all this, we should just do ". obs_funcs.sh" to load it via PATH
SRCFILE="`readlink $0 2>/dev/null || echo $0`"
SRC="`dirname $SRCFILE`"
case $SRC in
.*) DIR="`dirname $0`"
    SRC="`cd $DIR/$SRC; pwd`";;
*)  SRC="`cd $SRC; pwd`";;
esac
. "$SRC"/obs_funcs.sh

cmd="$1"
case "$cmd" in
"") usage; exit 0;;
esac
shift

case "$cmd" in
install) do_install $@;;
yovo2yoversion) bs_yovo2yoversion $@;;
yovo2cefversion) bs_yovo2cefversion $@;;
detect_os) echo $_os ;; # bs_detect_os already called
*) echo "Unknown cmd $cmd"; usage; exit 1;;
esac
