#!/bin/sh
# Commands related to building or installing Oblong packages on Linux, Mac, and Windows
# FIXME: hoist them out of obs_funcs.sh into individual files so we don't need this wrapper?
set -e

usage() {
    cat <<_EOF_
Usage: obs verb [args]
obs detect-ncores           - get number of CPU cores this computer has
obs detect-os               - get our os type/version identifier for the current os
obs get-major-version-git   - get major version number of current project from heavyweight git tags
obs get-version-git         - get version number of current project from heavyweight git tags
obs install pkg ...         - install tarball packages from $MASTER
obs download pkg ...        - download but do not unpack tarball packages from $MASTER"
obs list                    - list tarball packages available to install for $_os from $MASTER
obs yovo2cefversion VERSION - look up which version of cef the given version of g-speak (well, webthing) depends on
obs yovo2yoversion VERSION  - look up which version of yobuild the given version of g-speak depends on
obs apt-key-gen             - generate a fake gpg signing key in \$BS_APT_LOCALBUILD
obs apt-key-rm              - remove a fake gpg signing key
_EOF_
}

# If obs is properly installed, obs_funcs.sh will be on PATH
# but during development, we want to read obs_funcs.sh from same directory as obs, overriding installed one
SRCFILE="`readlink $0 2>/dev/null || echo $0`"
case "$SRCFILE" in
./obs) . ./obs_funcs.sh;;
*)     . obs_funcs.sh;;
esac

cmd="$1"
case "$cmd" in
--help|"") usage; exit 0;;
esac
shift

# Allow - as synonym for _ in command names
cmd="$(printf %s "$cmd" | tr - _)"

case "$cmd" in
detect_ncores)         bs_detect_ncores;;
detect_os)             echo $_os ;; # bs_detect_os already called
get_major_version_git) bs_get_major_version_git;;
get_version_git)       bs_get_version_git;;
install)               bs_install $@;;
download)              bs_download $@;;
pkg_list|list)         bs_pkg_list;;
yovo2cefversion)       bs_yovo2cefversion $@;;
yovo2yoversion)        bs_yovo2yoversion $@;;
apt_key_gen)           bs_apt_key_gen;;
apt_key_rm)            bs_apt_key_rm;;
*)                     echo "Unknown cmd $cmd"; usage; exit 1;;
esac
