#!/bin/sh
# postinst script for mezzanine
#
# see: dh_installdeb(1)

set -e
set -x

case "$1" in
    upgrade|install)
        # cleanup leftovers from previous upgrades (see bug 15792):
        rm -rf /etc/oblong/app-settings.protein.dpkg-old
        ;;
    abort-upgrade)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

# end of file
