usr/bin/fletcher                        usr/bin
usr/bin/matloc                          usr/bin
usr/bin/marple                          usr/bin

../../projects/mezzanine/init.d/fletcher                         etc/init.d/wb
../../projects/mezzanine/init.d/matloc                           etc/init.d/wb
../../projects/mezzanine/init.d/whiteboard                       etc/init.d/wb
../../projects/mezzanine/init.d/marple                           etc/init.d/wb
../../projects/mezzanine/init.d/qm-provisioner-bm                etc/init.d/wb
../../projects/mezzanine/init.d/qm-provisioner-ipcam             etc/init.d/wb

../../projects/mezzanine/systemd/fletcher.service                lib/systemd/system
../../projects/mezzanine/systemd/matloc.service                  lib/systemd/system
../../projects/mezzanine/systemd/matloc.service.d/radeon.conf    opt/oblong/mezzanine/systemd-drop-ins/matloc.service.d
../../projects/mezzanine/systemd/whiteboard.service              lib/systemd/system
../../projects/mezzanine/systemd/marple.service                  lib/systemd/system
../../projects/mezzanine/systemd/qm-provisioner-ipcam.service    lib/systemd/system

../../projects/mezzanine/init.d/helpers/_wbipcam.avigilon        etc/oblong/quartermaster
../../projects/mezzanine/init.d/helpers/_wbipcam.arecont         etc/oblong/quartermaster
../../projects/mezzanine/init.d/helpers/_wbipcam.eclipse         etc/oblong/quartermaster
../../projects/mezzanine/init.d/helpers/whiteboard.monitrc       etc/monit.d
